cmd_/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o := gcc -Wp,-MD,/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/i686-linux-gnu/4.9/include  -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -maccumulate-outgoing-args -Wa,-mtune=generic32 -ffreestanding -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO -DSTA_DRIVER_BUILD="\"20141022-1327\"" -g -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=mt7610u -DRESOURCE_PRE_ALLOC -DENHANCED_STAT_DISPLAY -I/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/include -DDOT11_VHT_AC -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DNEW_RATE_ADAPT_SUPPORT -DSTATS_COUNT_SUPPORT -DLED_CONTROL_SUPPORT -DRTMP_TEMPERATURE_TX_ALC -DMT76x0 -DRT65xx -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DA_BAND_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DCONFIG_ANDES_SUPPORT -DMT7610  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7610u_sta)" -c -o /home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/.tmp_alg_ags.o /home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.c

source_/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o := /home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \

/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/te/src/tp-link/mt7610u_wifi_sta_v3002_dpo_20130916/os/linux/../../rate_ctrl/alg_ags.o):
